version: '3'

services:
  app:
    build:
      context: node
    container_name: node-app
    ports: 
      - "3000:3000"
    volumes:
      - ./node:/usr/src/app

  db:
    image: mysql
    container_name: mysql-db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodeappdb
      - MYSQL_ROOT_PASSWORD=root
