version: '3'

services:
  nginx:
    build:
      context: nginx
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks: 
      - node-app-network
    depends_on:
      - app

  app:
    build:
      context: node
    image: node
    container_name: node-app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 100s node src/index.js
    volumes:
      - /usr/src/app
    networks: 
      - node-app-network
    depends_on:
      - db

  db:
    image: mysql:8.0.29
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    volumes: 
      - ./mysql/data:/var/lib/mysql
      - ./mysql/dump:/docker-entrypoint-initdb.d
    networks: 
      - node-app-network
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

networks: 
  node-app-network:
    driver: bridge