version: '3'

services:
  app:
    build:
      context: node
    image: node
    container_name: node-app
    ports: 
      - "3000:3000"
    volumes:
      - ./node:/usr/src/app
    networks: 
      - node-app-network
    depends_on:
      - db

  db:
    image: mysql
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    networks: 
      - node-app-network
    environment: 
      - MYSQL_DATABASE=nodeappdb
      - MYSQL_ROOT_PASSWORD=root

networks: 
  node-app-network:
    driver: bridge