version: '3'

services:
  app:
    build:
      context: node
    container_name: node-app
    ports: 
      - "3000:3000"

  db:
    build:
      context: mysql
    container_name: mysql-db
    restart: always
    tty: true
    